// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/games": {
            "post": {
                "description": "Create a new game between two players",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Create a new game",
                "parameters": [
                    {
                        "description": "Game creation data",
                        "name": "game",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ua_services_game-battle-service_internal_service.CreateGameRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ua_services_game-battle-service_internal_service.GameResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/games/active": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all active games for the current player",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Get active games",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ua_services_game-battle-service_internal_service.ActiveGamesResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/games/{gameId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get the current state of a game",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Get game state",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game ID",
                        "name": "gameId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ua_services_game-battle-service_internal_service.GameResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/games/{gameId}/actions": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Play an action in a game",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Play an action",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game ID",
                        "name": "gameId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Action data",
                        "name": "action",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ActionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ua_services_game-battle-service_internal_service.ActionResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/games/{gameId}/join": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Join an existing game as a player",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Join a game",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game ID",
                        "name": "gameId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ua_services_game-battle-service_internal_service.GameResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/games/{gameId}/mulligan": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Player decides whether to mulligan their hand",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Perform mulligan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game ID",
                        "name": "gameId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Mulligan decision",
                        "name": "mulligan",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.MulliganRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ua_services_game-battle-service_internal_service.GameResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/games/{gameId}/start": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Start a game that is waiting for players",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Start a game",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game ID",
                        "name": "gameId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ua_services_game-battle-service_internal_service.GameResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/games/{gameId}/surrender": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Surrender the current game",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Surrender game",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game ID",
                        "name": "gameId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ua_services_game-battle-service_internal_service.GameResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_handler.ActionRequest": {
            "type": "object",
            "required": [
                "action_type"
            ],
            "properties": {
                "action_data": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "action_type": {
                    "type": "string"
                }
            }
        },
        "internal_handler.MulliganRequest": {
            "type": "object",
            "properties": {
                "mulligan": {
                    "type": "boolean"
                }
            }
        },
        "models.Board": {
            "type": "object",
            "properties": {
                "character_zones": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/models.CardInPlay"
                        }
                    }
                },
                "field_zone": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.CardInPlay"
                    }
                }
            }
        },
        "models.Card": {
            "type": "object",
            "properties": {
                "ap_cost": {
                    "type": "integer"
                },
                "bp": {
                    "type": "integer"
                },
                "card_number": {
                    "description": "基礎卡號 (如: \"UA25BT-001\")",
                    "type": "string"
                },
                "card_type": {
                    "description": "-- CHARACTER, FIELD, EVENT, AP",
                    "type": "string"
                },
                "card_variant_id": {
                    "description": "完整變體ID (如: \"UA25BT-001-SR\", \"UA25BT-001-R\")",
                    "type": "string"
                },
                "characteristics": {
                    "description": "-- 特徵標籤",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "color": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "effect_text": {
                    "type": "string"
                },
                "energy_cost": {
                    "description": "-- 能源需求 {\"red\": 2, \"blue\": 1}",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "energy_produce": {
                    "description": "-- 能源產生 {\"red\": 1, \"blue\": 0}",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "id": {
                    "type": "string"
                },
                "image_url": {
                    "description": "稀有度特定圖片 URL",
                    "type": "string"
                },
                "keywords": {
                    "description": "-- 關鍵字 [レイド, 狙い撃ち, ダメージ2]",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "rarity": {
                    "type": "string"
                },
                "rarity_code": {
                    "description": "稀有度代碼 (\"C\", \"U\", \"R\", \"SR\", \"SEC\")",
                    "type": "string"
                },
                "trigger_effect": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "work_code": {
                    "description": "-- 作品編號 (前3碼)",
                    "type": "string"
                }
            }
        },
        "models.CardInPlay": {
            "type": "object",
            "properties": {
                "card": {
                    "$ref": "#/definitions/models.Card"
                },
                "modifiers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.CardModifier"
                    }
                },
                "owner": {
                    "type": "string"
                },
                "position": {
                    "$ref": "#/definitions/models.Position"
                },
                "status": {
                    "$ref": "#/definitions/models.CardStatus"
                }
            }
        },
        "models.CardModifier": {
            "type": "object",
            "properties": {
                "applied_at": {
                    "type": "integer"
                },
                "duration": {
                    "type": "integer"
                },
                "source": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "value": {}
            }
        },
        "models.CardStatus": {
            "type": "object",
            "properties": {
                "can_act": {
                    "type": "boolean"
                },
                "can_attack": {
                    "type": "boolean"
                },
                "can_block": {
                    "type": "boolean"
                },
                "is_exhausted": {
                    "type": "boolean"
                }
            }
        },
        "models.GameAction": {
            "type": "object",
            "properties": {
                "action_data": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "action_type": {
                    "type": "string"
                },
                "error_msg": {
                    "type": "string"
                },
                "game_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_valid": {
                    "type": "boolean"
                },
                "phase": {
                    "$ref": "#/definitions/models.Phase"
                },
                "player_id": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "turn": {
                    "type": "integer"
                }
            }
        },
        "models.GameState": {
            "type": "object",
            "properties": {
                "action_log": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.GameAction"
                    }
                },
                "active_player": {
                    "type": "string"
                },
                "board": {
                    "$ref": "#/definitions/models.Board"
                },
                "first_player": {
                    "description": "先攻玩家ID",
                    "type": "string"
                },
                "life_area_setup": {
                    "description": "記錄是否已設置生命區",
                    "type": "boolean"
                },
                "mulligan_completed": {
                    "description": "記錄每個玩家是否完成調度",
                    "type": "object",
                    "additionalProperties": {
                        "type": "boolean"
                    }
                },
                "phase": {
                    "$ref": "#/definitions/models.Phase"
                },
                "players": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/models.Player"
                    }
                },
                "turn": {
                    "type": "integer"
                }
            }
        },
        "models.GameStatus": {
            "type": "string",
            "enum": [
                "WAITING",
                "IN_PROGRESS",
                "COMPLETED",
                "ABANDONED"
            ],
            "x-enum-varnames": [
                "GameStatusWaiting",
                "GameStatusInProgress",
                "GameStatusCompleted",
                "GameStatusAbandoned"
            ]
        },
        "models.Phase": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3,
                4
            ],
            "x-enum-varnames": [
                "StartPhase",
                "MovePhase",
                "MainPhase",
                "AttackPhase",
                "EndPhase"
            ]
        },
        "models.Player": {
            "type": "object",
            "properties": {
                "ap": {
                    "type": "integer"
                },
                "characters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.CardInPlay"
                    }
                },
                "deck": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Card"
                    }
                },
                "energy": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.CardInPlay"
                    }
                },
                "extra_draw_used": {
                    "description": "本回合是否已使用額外抽卡",
                    "type": "boolean"
                },
                "fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.CardInPlay"
                    }
                },
                "graveyard": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Card"
                    }
                },
                "hand": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Card"
                    }
                },
                "id": {
                    "type": "string"
                },
                "life_area": {
                    "description": "生命區：7張背面朝上的卡片，遊戲開始時從卡組頂部設置",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Card"
                    }
                },
                "max_ap": {
                    "type": "integer"
                },
                "removed_cards": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Card"
                    }
                }
            }
        },
        "models.Position": {
            "type": "object",
            "properties": {
                "slot": {
                    "type": "integer"
                },
                "zone": {
                    "type": "integer"
                }
            }
        },
        "ua_services_game-battle-service_internal_service.ActionResponse": {
            "type": "object",
            "properties": {
                "effects": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ua_services_game-battle-service_internal_service.EffectResult"
                    }
                },
                "error": {
                    "type": "string"
                },
                "events_triggered": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ua_services_game-battle-service_internal_service.GameEvent"
                    }
                },
                "game_state": {
                    "$ref": "#/definitions/models.GameState"
                },
                "next_phase": {
                    "$ref": "#/definitions/models.Phase"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "ua_services_game-battle-service_internal_service.ActiveGamesResponse": {
            "type": "object",
            "properties": {
                "games": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ua_services_game-battle-service_internal_service.GameInfo"
                    }
                }
            }
        },
        "ua_services_game-battle-service_internal_service.CreateGameRequest": {
            "type": "object",
            "required": [
                "game_mode",
                "player1_deck",
                "player1_id",
                "player2_deck",
                "player2_id"
            ],
            "properties": {
                "game_mode": {
                    "type": "string"
                },
                "player1_deck": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Card"
                    }
                },
                "player1_id": {
                    "type": "string"
                },
                "player2_deck": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Card"
                    }
                },
                "player2_id": {
                    "type": "string"
                }
            }
        },
        "ua_services_game-battle-service_internal_service.EffectResult": {
            "type": "object",
            "properties": {
                "applied": {
                    "type": "boolean"
                },
                "description": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "target": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "value": {}
            }
        },
        "ua_services_game-battle-service_internal_service.GameEvent": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "additionalProperties": true
                },
                "source": {
                    "type": "string"
                },
                "target": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "ua_services_game-battle-service_internal_service.GameInfo": {
            "type": "object",
            "properties": {
                "active_player": {
                    "type": "string"
                },
                "completed_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "current_turn": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "phase": {
                    "$ref": "#/definitions/models.Phase"
                },
                "player1_id": {
                    "type": "string"
                },
                "player2_id": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/models.GameStatus"
                },
                "updated_at": {
                    "type": "string"
                },
                "winner": {
                    "type": "string"
                }
            }
        },
        "ua_services_game-battle-service_internal_service.GameResponse": {
            "type": "object",
            "properties": {
                "game": {
                    "$ref": "#/definitions/ua_services_game-battle-service_internal_service.GameInfo"
                },
                "game_state": {
                    "$ref": "#/definitions/models.GameState"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "utils.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8004",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "UA Game Battle Service API",
	Description:      "Real-time game battle microservice for UA Card Battle Game",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
